
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password:
 
development:
  <<: *default
  database: hackitz_otterlog_dev

test: &test
  <<: *default
  database: hackitz_otterlog_test

production:
  <<: *default
  database: hackitz_otterlog_prod
  pool: 100

cucumber:
  <<: *test
